---
title: "Applications"
sidebar: false
---

### Participant Applications

<div class="announcement-box">

<p><span style="color: #2a446a; font-weight: bold;">Applications for participants are now open! </span></p>

If you are interested, please take a look at this year's <span style="color: #2a446a; font-weight: bold;"> <a href=projects.qmd style="font-weight: bold;">projects</a></span> and apply using this <span style="color: #2a446a; font-weight: bold;"> <a href="https://forms.gle/Vqzor7NHQ5YXie5aA" style="font-weight: bold;">form</a></span>.</p>

<p> LOGML is primarily designed for early-career researchers, including PhD students, postdocs, and industry professionals. 
While applications from Master’s and Bachelor’s students are welcome, priority will be given to applicants at the doctoral level and beyond.</p>

What to Expect:

* <strong>Collaborative Projects:</strong> Placed in a small, focused research group (typically five people), you will actively contribute to a week-long research project under the guidance of an expert mentor.

* <strong>High-Level Content:</strong> Access talks and tutorials by world-renowned leaders in Mathematics and Machine Learning.

* <strong>Community:</strong> Participate in fun social events, poster sessions, and networking events designed to foster long-term professional relationships.

The registration fee for accepted applicants is **£325 for students (PhD, MSc, BSc), £400 for Postdocs and £500 for people working in industry**. 
We also offer a limited number of highly competitive fee waivers and travel contributions for exceptional applicants in genuine financial struggle.  

<p><br><strong style="color: #2a446a">Applications close on 1 May 2026, AoE (Anywhere on Earth).</strong></p>

</div>

### Mentor Applications

<div class="announcement-box">

<p><span style="color: #2a446a; font-weight: bold;">Applications for this cycle are now closed! </span></p>

<p>Please find a list of accepted mentors <a href="projects.qmd">here</a>.</p>

<p>Mentors lead a small group of passionate, early-career researchers on a week-long project of their choosing at the intersection of geometry and machine learning.</p>

<p>LOGML is more than a summer school; it is an incubator for innovation. Several working groups initiated at LOGML have evolved into long-term collaborations, resulting in publications at top-tier venues such as NeurIPS, ICLR, and TMLR (see the full list <a href="index.qmd">here</a>). </p>


What to Expect:

* <strong>Collaborative Research:</strong> You will steer a team of approximately five researchers, working closely on a well-defined project. While 15 hours of the week are officially earmarked for project time, the high energy of the event often inspires groups to dedicate more.

* <strong>Tangible Outcomes:</strong> The LOGML experience is intensive. With one week to work, success comes from focusing on achievable milestones—such as adapting algorithms to new datasets, pilot-testing a theoretical idea, or laying the foundation for a future paper.

* <strong>Networking & Engagement:</strong> Beyond project work, the week features keynote lectures from leading figures in the field, fun social activities, and several networking events.

Financial support for travel and accommodation will also be provided for all accepted mentors.</p>

</div>
